apiVersion: apps/v1
kind: Deployment
metadata:
  name: @name
  namespace: infra
spec:
  selector:
    matchLabels:
      app: @name
  replicas: 1
  template:
    metadata:
      labels:
        app: @name
    spec:
      nodeSelector:
        xremote: @node_label
      containers:
        - name: relay
          image: hub.autox.ai/infra/xremote/relay-server:@label
          ports:
            - name: server
              containerPort: 51117
              protocol: UDP
          imagePullPolicy: IfNotPresent
          env:
            - name: RUN_XREMOTE_SERVER_MODE
              value: production
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          volumeMounts:
            - name: config
              mountPath: /opt/relay_server/config/relay/production.toml
              subPath: production.toml
            - name: log
              mountPath: /opt/relay_server/log
          command: ["/bin/bash"]
          args: ["-c", "/opt/relay_server/run.sh"]
      volumes:
        - name: config
          configMap:
            name: @name
        - name: log
          persistentVolumeClaim:
            claimName: xremote-log
