apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xremote-log
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: csi-nfs-sc-xremote
