apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
  namespace: default
  uid: cf924c2d-8a14-4101-8a30-68ae515a9ad2
  labels:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
    helm.sh/chart: redis-16.8.2
secrets:
  - name: redis-token-xvbnm
automountServiceAccountToken: true
