apiVersion: v1
kind: ConfigMap
metadata:
  name: @name
  namespace: infra
data:
  production.toml: |-
    debug = false

    [server]
    listen_port = @port

    [config_item]
    city_list = ["beijing", "shenzhen", "guangzhou"]

    [nats]
    nats_addr = "@nats_addr"
    nats_port = @nats_port
    tls = false
    user = "@nats_user"
    password = "@nats_password"
