version: "3.4"
# reboot: docker-compose up -d [service]
services:
  nginx:
    image: "nginx:latest"
    container_name: "xremote_nginx"
    network_mode: "host"
    volumes:
      - "${HOME}/nginx/nginx.conf:/etc/nginx/nginx.conf"
    restart: always
