kind: Service
apiVersion: v1
metadata:
  name: @name
  namespace: infra
spec:
  ports:
    - name: server
      port: 51116
      targetPort: 51116
      protocol: UDP
  selector:
    app: @name
  sessionAffinity: ClientIP
