apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: nats
      app.kubernetes.io/name: nats
      helm.sh/chart: nats-7.1.13
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: nats
        app.kubernetes.io/name: nats
        helm.sh/chart: nats-7.1.13
    spec:
      volumes:
        - name: config
          configMap:
            name: nats
      containers:
        - name: nats
          image: docker.io/bitnami/nats:2.7.4-debian-10-r17
          ports:
            - name: client
              containerPort: 4222
              protocol: TCP
            - name: cluster
              containerPort: 6222
              protocol: TCP
            - name: monitoring
              containerPort: 8222
              protocol: TCP
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: NATS_FILENAME
              value: nats-server
          resources: {}
          volumeMounts:
            - name: config
              mountPath: /bitnami/nats/conf/nats-server.conf
              subPath: nats-server.conf
          livenessProbe:
            httpGet:
              path: /
              port: monitoring
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /
              port: monitoring
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: nats
                    app.kubernetes.io/name: nats
                namespaces:
                  - default
                topologyKey: kubernetes.io/hostname
      schedulerName: default-scheduler
  serviceName: nats-headless
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  revisionHistoryLimit: 10
